---
# Monitoring role - Handlers

- name: Restart node-exporter
  systemd:
    name: prometheus-node-exporter
    state: restarted

- name: Restart collectd
  systemd:
    name: collectd
    state: restarted

- name: Restart rsyslog
  systemd:
    name: rsyslog
    state: restarted
